//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp11
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int ID { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string Patronimic { get; set; }
        public string PhoneNumber { get; set; }
        public int Gender { get; set; }
    
        public virtual gender gender1 { get; set; }
    }
}
